
security:
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        
    providers:
        gestionUser:
            
            entity:
                class: AppBundle:User
                property: nom
                
        in_memory:
            memory: 
                users:
                    admin:
                        password: vivi
                        roles: 'ROLE_ADMIN'
                    

    firewalls:
       
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:     
            pattern : ^/
            anonymous: true
            provider: in_memory
            form_login:
                check_path: loginCheck
                login_path: home
            logout:
                path: loginOut
                target: /
                
        admin:
            pattern: ^/admin
            anonymous: false
            provider: in_memory
            # le formulaire de login pour que symfony sache où il campe
            form_login:
                check_path: loginCheck
                login_path: home
            logout:
                path: loginOut
                target: /
                
    encoders:
        Symfony\Component\Security\Core\User\User:  plaintext
        AppBundle\Entity\User:
            algorithm: plaintext
            ignore_case: false
            
    access_control:   
        # Un admin ou un user classique peut ajouter une annonce ... quelque chose d'étrange est ici ....
        - { path: ^/admin/projet , roles: [ROLE_ADMIN , ROLE_USER] }       
     
            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
